const ADDING_PERSON: string = 'ADDING_PERSON';
const ADDED_PERSON_SUCCESS: string = 'ADDED_PERSON_SUCCESS';
const ADDED_PERSON_FAIL: string = 'ADDED_PERSON_FAIL';

export {ADDING_PERSON, ADDED_PERSON_SUCCESS, ADDED_PERSON_FAIL};
